Add rails controller testing gem so that I can use `assigns`
Because:

```
[2] pry(#<IssuesControllerTest>)> assigns(:issues)
NoMethodError: assigns has been extracted to a gem. To continue using it,
        add `gem 'rails-controller-testing'` to your Gemfile.
```